resolver: nightly-2016-10-25
packages:
- '.'



compiler: ghcjs-0.2.1.820161025_ghc-8.0.1
compiler-check: match-exact  

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.820161025_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/untested/ghc-8.0-2016-10-25-nightly-2016-10-25-820161025.tar.gz
          sha1: ca05f23ab6af89803a9fa8ce7241ebdd2eee7dae

extra-deps: []

flags: {}

extra-package-dbs: []
